name: C/C++ CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: |
        git clone https://github.com/strasdat/Sophus
        cd Sophus && mkdir build && cd build && cmake .. && make install
        sudo apt install libeigen3-dev
        sudo apt-get install libopencv-dev
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest
      
